use super::types::*;

pub fn environment_definitions() -> Vec<EnvironmentDefinition> {
    vec![
        // 1. Java
        EnvironmentDefinition {
            id: EnvironmentKind::Java,
            name: "Java".to_string(),
            group: "编程语言".to_string(),
            description: "JDK 运行时和开发工具链".to_string(),
            logo_id: EnvironmentKind::Java,
            accent_color: "#e76f00".to_string(),
            env_vars: vec!["JAVA_HOME".to_string()],
            path_entries: vec!["bin".to_string()],
            install_type: InstallType::Archive,
            vendors: vec![
                VendorOption {
                    id: "temurin".to_string(),
                    name: "Eclipse Temurin".to_string(),
                    homepage: "https://adoptium.net".to_string(),
                },
                VendorOption {
                    id: "zulu".to_string(),
                    name: "Azul Zulu".to_string(),
                    homepage: "https://www.azul.com/downloads".to_string(),
                },
                VendorOption {
                    id: "liberica".to_string(),
                    name: "BellSoft Liberica".to_string(),
                    homepage: "https://bell-sw.com/libericajdk".to_string(),
                },
                VendorOption {
                    id: "oracle".to_string(),
                    name: "Oracle JDK".to_string(),
                    homepage: "https://www.oracle.com/java/technologies/downloads".to_string(),
                },
            ],
        },
        // 2. Python
        EnvironmentDefinition {
            id: EnvironmentKind::Python,
            name: "Python".to_string(),
            group: "Python".to_string(),
            description: "CPython 官方解释器和 pip 工具链".to_string(),
            logo_id: EnvironmentKind::Python,
            accent_color: "#3776ab".to_string(),
            env_vars: vec!["PYTHON_HOME".to_string()],
            path_entries: vec!["".to_string(), "Scripts".to_string()],
            install_type: InstallType::Installer,
            vendors: vec![VendorOption {
                id: "cpython".to_string(),
                name: "Python 官方".to_string(),
                homepage: "https://www.python.org/downloads/windows/".to_string(),
            }],
        },
        // 3. Conda
        EnvironmentDefinition {
            id: EnvironmentKind::Conda,
            name: "Conda".to_string(),
            group: "Python".to_string(),
            description: "Miniconda / Anaconda 发行版和基础环境".to_string(),
            logo_id: EnvironmentKind::Conda,
            accent_color: "#43a047".to_string(),
            env_vars: vec!["CONDA_HOME".to_string()],
            path_entries: vec![
                "Scripts".to_string(),
                "Library\\bin".to_string(),
                "condabin".to_string(),
            ],
            install_type: InstallType::Installer,
            vendors: vec![
                VendorOption {
                    id: "miniconda".to_string(),
                    name: "Miniconda".to_string(),
                    homepage: "https://docs.anaconda.com/miniconda".to_string(),
                },
                VendorOption {
                    id: "anaconda".to_string(),
                    name: "Anaconda Distribution".to_string(),
                    homepage: "https://www.anaconda.com/download".to_string(),
                },
            ],
        },
        // 4. Go
        EnvironmentDefinition {
            id: EnvironmentKind::Go,
            name: "Go".to_string(),
            group: "编程语言".to_string(),
            description: "Go 语言运行时和工具链".to_string(),
            logo_id: EnvironmentKind::Go,
            accent_color: "#00add8".to_string(),
            env_vars: vec!["GOROOT".to_string()],
            path_entries: vec!["bin".to_string()],
            install_type: InstallType::Archive,
            vendors: vec![VendorOption {
                id: "golang".to_string(),
                name: "Go 官方".to_string(),
                homepage: "https://go.dev/dl".to_string(),
            }],
        },
        // 5. Node
        EnvironmentDefinition {
            id: EnvironmentKind::Node,
            name: "Node.js".to_string(),
            group: "JavaScript".to_string(),
            description: "Node.js 官方运行时和 npm 工具链".to_string(),
            logo_id: EnvironmentKind::Node,
            accent_color: "#339933".to_string(),
            env_vars: vec!["NODE_HOME".to_string()],
            path_entries: vec!["".to_string()],
            install_type: InstallType::Archive,
            vendors: vec![VendorOption {
                id: "nodejs".to_string(),
                name: "Node.js 官方".to_string(),
                homepage: "https://nodejs.org/download/release/".to_string(),
            }],
        },
        // 6. Nvm
        EnvironmentDefinition {
            id: EnvironmentKind::Nvm,
            name: "nvm-windows".to_string(),
            group: "JavaScript".to_string(),
            description: "Windows Node.js 多版本管理器".to_string(),
            logo_id: EnvironmentKind::Nvm,
            accent_color: "#2f855a".to_string(),
            env_vars: vec!["NVM_HOME".to_string(), "NVM_SYMLINK".to_string()],
            path_entries: vec!["".to_string(), "nodejs".to_string()],
            install_type: InstallType::Archive,
            vendors: vec![VendorOption {
                id: "coreybutler".to_string(),
                name: "nvm-windows".to_string(),
                homepage: "https://github.com/coreybutler/nvm-windows".to_string(),
            }],
        },
        // 7. Maven
        EnvironmentDefinition {
            id: EnvironmentKind::Maven,
            name: "Maven".to_string(),
            group: "构建工具".to_string(),
            description: "Java 项目构建和依赖管理".to_string(),
            logo_id: EnvironmentKind::Maven,
            accent_color: "#c71a36".to_string(),
            env_vars: vec!["MAVEN_HOME".to_string()],
            path_entries: vec!["bin".to_string()],
            install_type: InstallType::Archive,
            vendors: vec![VendorOption {
                id: "apache".to_string(),
                name: "Apache Maven".to_string(),
                homepage: "https://maven.apache.org/download.cgi".to_string(),
            }],
        },
        // 8. Gradle
        EnvironmentDefinition {
            id: EnvironmentKind::Gradle,
            name: "Gradle".to_string(),
            group: "构建工具".to_string(),
            description: "Gradle 构建工具和 Wrapper 生态".to_string(),
            logo_id: EnvironmentKind::Gradle,
            accent_color: "#02303a".to_string(),
            env_vars: vec!["GRADLE_HOME".to_string()],
            path_entries: vec!["bin".to_string()],
            install_type: InstallType::Archive,
            vendors: vec![VendorOption {
                id: "gradle".to_string(),
                name: "Gradle 官方".to_string(),
                homepage: "https://gradle.org/releases/".to_string(),
            }],
        },
        // 9. Cmake
        EnvironmentDefinition {
            id: EnvironmentKind::Cmake,
            name: "CMake".to_string(),
            group: "构建工具".to_string(),
            description: "跨平台 C/C++ 构建系统".to_string(),
            logo_id: EnvironmentKind::Cmake,
            accent_color: "#064f8c".to_string(),
            env_vars: vec!["CMAKE_HOME".to_string()],
            path_entries: vec!["bin".to_string()],
            install_type: InstallType::Archive,
            vendors: vec![VendorOption {
                id: "kitware".to_string(),
                name: "Kitware CMake".to_string(),
                homepage: "https://cmake.org/download/".to_string(),
            }],
        },
        // 10. Ninja
        EnvironmentDefinition {
            id: EnvironmentKind::Ninja,
            name: "Ninja".to_string(),
            group: "构建工具".to_string(),
            description: "高速小型构建执行器".to_string(),
            logo_id: EnvironmentKind::Ninja,
            accent_color: "#d64a1a".to_string(),
            env_vars: vec!["NINJA_HOME".to_string()],
            path_entries: vec!["".to_string()],
            install_type: InstallType::Archive,
            vendors: vec![VendorOption {
                id: "ninja-build".to_string(),
                name: "Ninja Build".to_string(),
                homepage: "https://github.com/ninja-build/ninja/releases".to_string(),
            }],
        },
        // 11. Cpp
        EnvironmentDefinition {
            id: EnvironmentKind::Cpp,
            name: "C++".to_string(),
            group: "编程语言".to_string(),
            description: "LLVM-MinGW C/C++ 编译工具链".to_string(),
            logo_id: EnvironmentKind::Cpp,
            accent_color: "#00599c".to_string(),
            env_vars: vec!["LLVM_MINGW_HOME".to_string()],
            path_entries: vec!["bin".to_string()],
            install_type: InstallType::Archive,
            vendors: vec![VendorOption {
                id: "llvm-mingw".to_string(),
                name: "LLVM-MinGW".to_string(),
                homepage: "https://github.com/mstorsjo/llvm-mingw".to_string(),
            }],
        },
        // 12. Lua
        EnvironmentDefinition {
            id: EnvironmentKind::Lua,
            name: "Lua".to_string(),
            group: "编程语言".to_string(),
            description: "Lua 解释器和字节码编译器".to_string(),
            logo_id: EnvironmentKind::Lua,
            accent_color: "#000080".to_string(),
            env_vars: vec!["LUA_HOME".to_string()],
            path_entries: vec!["".to_string()],
            install_type: InstallType::Archive,
            vendors: vec![VendorOption {
                id: "luabinaries".to_string(),
                name: "LuaBinaries".to_string(),
                homepage: "https://luabinaries.sourceforge.net/download.html".to_string(),
            }],
        },
        // 13. Rust
        EnvironmentDefinition {
            id: EnvironmentKind::Rust,
            name: "Rust".to_string(),
            group: "编程语言".to_string(),
            description: "Rustup、Cargo 和 Rust 工具链".to_string(),
            logo_id: EnvironmentKind::Rust,
            accent_color: "#a72145".to_string(),
            env_vars: vec!["CARGO_HOME".to_string(), "RUSTUP_HOME".to_string()],
            path_entries: vec!["cargo\\bin".to_string()],
            install_type: InstallType::Installer,
            vendors: vec![VendorOption {
                id: "rustup".to_string(),
                name: "Rustup".to_string(),
                homepage: "https://rustup.rs".to_string(),
            }],
        },
        // 14. Dotnet
        EnvironmentDefinition {
            id: EnvironmentKind::Dotnet,
            name: ".NET SDK".to_string(),
            group: "编程语言".to_string(),
            description: ".NET SDK、CLI 和运行时".to_string(),
            logo_id: EnvironmentKind::Dotnet,
            accent_color: "#512bd4".to_string(),
            env_vars: vec!["DOTNET_ROOT".to_string()],
            path_entries: vec!["".to_string()],
            install_type: InstallType::Archive,
            vendors: vec![VendorOption {
                id: "microsoft".to_string(),
                name: "Microsoft .NET".to_string(),
                homepage: "https://dotnet.microsoft.com/download".to_string(),
            }],
        },
        // 15. Php
        EnvironmentDefinition {
            id: EnvironmentKind::Php,
            name: "PHP".to_string(),
            group: "编程语言".to_string(),
            description: "PHP Windows ZIP 发行版".to_string(),
            logo_id: EnvironmentKind::Php,
            accent_color: "#777bb4".to_string(),
            env_vars: vec!["PHP_HOME".to_string()],
            path_entries: vec!["".to_string()],
            install_type: InstallType::Archive,
            vendors: vec![VendorOption {
                id: "windows".to_string(),
                name: "PHP for Windows".to_string(),
                homepage: "https://windows.php.net/download/".to_string(),
            }],
        },
        // 16. Ruby
        EnvironmentDefinition {
            id: EnvironmentKind::Ruby,
            name: "Ruby".to_string(),
            group: "编程语言".to_string(),
            description: "RubyInstaller for Windows".to_string(),
            logo_id: EnvironmentKind::Ruby,
            accent_color: "#cc342d".to_string(),
            env_vars: vec!["RUBY_HOME".to_string()],
            path_entries: vec!["bin".to_string()],
            install_type: InstallType::Installer,
            vendors: vec![VendorOption {
                id: "rubyinstaller".to_string(),
                name: "RubyInstaller".to_string(),
                homepage: "https://rubyinstaller.org/downloads/".to_string(),
            }],
        },
        // 17. Flutter
        EnvironmentDefinition {
            id: EnvironmentKind::Flutter,
            name: "Flutter".to_string(),
            group: "移动开发".to_string(),
            description: "Flutter SDK 和 Dart 工具链".to_string(),
            logo_id: EnvironmentKind::Flutter,
            accent_color: "#02569b".to_string(),
            env_vars: vec!["FLUTTER_HOME".to_string()],
            path_entries: vec!["bin".to_string()],
            install_type: InstallType::Archive,
            vendors: vec![VendorOption {
                id: "google".to_string(),
                name: "Flutter 官方".to_string(),
                homepage: "https://docs.flutter.dev/get-started/install/windows".to_string(),
            }],
        },
        // 18. Android
        EnvironmentDefinition {
            id: EnvironmentKind::Android,
            name: "Android SDK".to_string(),
            group: "移动开发".to_string(),
            description: "Android Command Line Tools 和 SDK 根目录".to_string(),
            logo_id: EnvironmentKind::Android,
            accent_color: "#3ddc84".to_string(),
            env_vars: vec!["ANDROID_HOME".to_string(), "ANDROID_SDK_ROOT".to_string()],
            path_entries: vec![
                "cmdline-tools\\bin".to_string(),
                "platform-tools".to_string(),
            ],
            install_type: InstallType::Archive,
            vendors: vec![VendorOption {
                id: "google".to_string(),
                name: "Android Command Line Tools".to_string(),
                homepage: "https://developer.android.com/studio".to_string(),
            }],
        },
        // 19. Mysql
        EnvironmentDefinition {
            id: EnvironmentKind::Mysql,
            name: "MySQL".to_string(),
            group: "数据库".to_string(),
            description: "MySQL Community Server ZIP 部署".to_string(),
            logo_id: EnvironmentKind::Mysql,
            accent_color: "#00758f".to_string(),
            env_vars: vec!["MYSQL_HOME".to_string()],
            path_entries: vec!["bin".to_string()],
            install_type: InstallType::Archive,
            vendors: vec![VendorOption {
                id: "community".to_string(),
                name: "MySQL Community Server".to_string(),
                homepage: "https://dev.mysql.com/downloads/mysql/".to_string(),
            }],
        },
        // 20. Postgresql
        EnvironmentDefinition {
            id: EnvironmentKind::Postgresql,
            name: "PostgreSQL".to_string(),
            group: "数据库".to_string(),
            description: "PostgreSQL Windows 二进制包部署".to_string(),
            logo_id: EnvironmentKind::Postgresql,
            accent_color: "#336791".to_string(),
            env_vars: vec!["PG_HOME".to_string()],
            path_entries: vec!["bin".to_string()],
            install_type: InstallType::Archive,
            vendors: vec![VendorOption {
                id: "edb".to_string(),
                name: "EDB PostgreSQL Binaries".to_string(),
                homepage: "https://www.enterprisedb.com/download-postgresql-binaries"
                    .to_string(),
            }],
        },
        // 21. Mongodb
        EnvironmentDefinition {
            id: EnvironmentKind::Mongodb,
            name: "MongoDB".to_string(),
            group: "数据库".to_string(),
            description: "MongoDB Community Server ZIP 部署".to_string(),
            logo_id: EnvironmentKind::Mongodb,
            accent_color: "#47a248".to_string(),
            env_vars: vec!["MONGODB_HOME".to_string()],
            path_entries: vec!["bin".to_string()],
            install_type: InstallType::Archive,
            vendors: vec![VendorOption {
                id: "community".to_string(),
                name: "MongoDB Community Server".to_string(),
                homepage: "https://www.mongodb.com/try/download/community".to_string(),
            }],
        },
        // 22. Redis
        EnvironmentDefinition {
            id: EnvironmentKind::Redis,
            name: "Redis".to_string(),
            group: "数据库".to_string(),
            description: "Windows Redis 兼容开发运行时".to_string(),
            logo_id: EnvironmentKind::Redis,
            accent_color: "#dc342d".to_string(),
            env_vars: vec!["REDIS_HOME".to_string()],
            path_entries: vec!["".to_string()],
            install_type: InstallType::Archive,
            vendors: vec![VendorOption {
                id: "redis-windows".to_string(),
                name: "Redis Windows".to_string(),
                homepage: "https://github.com/tporadowski/redis/releases".to_string(),
            }],
        },
        // 23. Sqlite
        EnvironmentDefinition {
            id: EnvironmentKind::Sqlite,
            name: "SQLite".to_string(),
            group: "数据库".to_string(),
            description: "SQLite 命令行工具包".to_string(),
            logo_id: EnvironmentKind::Sqlite,
            accent_color: "#003b57".to_string(),
            env_vars: vec!["SQLITE_HOME".to_string()],
            path_entries: vec!["".to_string()],
            install_type: InstallType::Archive,
            vendors: vec![VendorOption {
                id: "sqlite".to_string(),
                name: "SQLite Tools".to_string(),
                homepage: "https://www.sqlite.org/download.html".to_string(),
            }],
        },
    ]
}
