import type { EnvironmentDefinition } from "./types";

export const environmentDefinitions: EnvironmentDefinition[] = [
  {
    id: "java",
    name: "Java",
    group: "编程语言",
    description: "JDK 运行时和开发工具链",
    logoId: "java",
    accentColor: "#e76f00",
    envVars: ["JAVA_HOME"],
    pathEntries: ["bin"],
    installType: "archive",
    vendors: [
      {
        id: "temurin",
        name: "Eclipse Temurin",
        homepage: "https://adoptium.net",
      },
      {
        id: "zulu",
        name: "Azul Zulu",
        homepage: "https://www.azul.com/downloads",
      },
      {
        id: "liberica",
        name: "BellSoft Liberica",
        homepage: "https://bell-sw.com/libericajdk",
      },
      {
        id: "oracle",
        name: "Oracle JDK",
        homepage: "https://www.oracle.com/java/technologies/downloads",
      },
    ],
  },
  {
    id: "python",
    name: "Python",
    group: "Python",
    description: "CPython 官方解释器和 pip 工具链",
    logoId: "python",
    accentColor: "#3776ab",
    envVars: ["PYTHON_HOME"],
    pathEntries: ["", "Scripts"],
    installType: "installer",
    vendors: [
      {
        id: "cpython",
        name: "Python 官方",
        homepage: "https://www.python.org/downloads/windows/",
      },
    ],
  },
  {
    id: "conda",
    name: "Conda",
    group: "Python",
    description: "Miniconda / Anaconda 发行版和基础环境",
    logoId: "conda",
    accentColor: "#43a047",
    envVars: ["CONDA_HOME"],
    pathEntries: ["Scripts", "Library\\bin", "condabin"],
    installType: "installer",
    vendors: [
      {
        id: "miniconda",
        name: "Miniconda",
        homepage: "https://docs.anaconda.com/miniconda",
      },
      {
        id: "anaconda",
        name: "Anaconda Distribution",
        homepage: "https://www.anaconda.com/download",
      },
    ],
  },
  {
    id: "go",
    name: "Go",
    group: "编程语言",
    description: "Go 语言运行时和工具链",
    logoId: "go",
    accentColor: "#00add8",
    envVars: ["GOROOT"],
    pathEntries: ["bin"],
    installType: "archive",
    vendors: [
      {
        id: "golang",
        name: "Go 官方",
        homepage: "https://go.dev/dl",
      },
    ],
  },
  {
    id: "node",
    name: "Node.js",
    group: "JavaScript",
    description: "Node.js 官方运行时和 npm 工具链",
    logoId: "node",
    accentColor: "#339933",
    envVars: ["NODE_HOME"],
    pathEntries: [""],
    installType: "archive",
    vendors: [
      {
        id: "nodejs",
        name: "Node.js 官方",
        homepage: "https://nodejs.org/download/release/",
      },
    ],
  },
  {
    id: "nvm",
    name: "nvm-windows",
    group: "JavaScript",
    description: "Windows Node.js 多版本管理器",
    logoId: "nvm",
    accentColor: "#2f855a",
    envVars: ["NVM_HOME", "NVM_SYMLINK"],
    pathEntries: ["", "nodejs"],
    installType: "archive",
    vendors: [
      {
        id: "coreybutler",
        name: "nvm-windows",
        homepage: "https://github.com/coreybutler/nvm-windows",
      },
    ],
  },
  {
    id: "maven",
    name: "Maven",
    group: "构建工具",
    description: "Java 项目构建和依赖管理",
    logoId: "maven",
    accentColor: "#c71a36",
    envVars: ["MAVEN_HOME"],
    pathEntries: ["bin"],
    installType: "archive",
    vendors: [
      {
        id: "apache",
        name: "Apache Maven",
        homepage: "https://maven.apache.org/download.cgi",
      },
    ],
  },
];
