import type { EnvironmentDefinition } from "./types";

export const environmentDefinitions: EnvironmentDefinition[] = [
  {
    id: "java",
    name: "Java",
    group: "编程语言",
    description: "JDK 运行时和开发工具链",
    logoId: "java",
    accentColor: "#e76f00",
    envVars: ["JAVA_HOME"],
    pathEntries: ["bin"],
    installType: "archive",
    vendors: [
      {
        id: "temurin",
        name: "Eclipse Temurin",
        homepage: "https://adoptium.net",
      },
      {
        id: "zulu",
        name: "Azul Zulu",
        homepage: "https://www.azul.com/downloads",
      },
      {
        id: "liberica",
        name: "BellSoft Liberica",
        homepage: "https://bell-sw.com/libericajdk",
      },
      {
        id: "oracle",
        name: "Oracle JDK",
        homepage: "https://www.oracle.com/java/technologies/downloads",
      },
    ],
  },
  {
    id: "python",
    name: "Python",
    group: "Python",
    description: "CPython 官方解释器和 pip 工具链",
    logoId: "python",
    accentColor: "#3776ab",
    envVars: ["PYTHON_HOME"],
    pathEntries: ["", "Scripts"],
    installType: "installer",
    vendors: [
      {
        id: "cpython",
        name: "Python 官方",
        homepage: "https://www.python.org/downloads/windows/",
      },
    ],
  },
  {
    id: "conda",
    name: "Conda",
    group: "Python",
    description: "Miniconda / Anaconda 发行版和基础环境",
    logoId: "conda",
    accentColor: "#43a047",
    envVars: ["CONDA_HOME"],
    pathEntries: ["Scripts", "Library\\bin", "condabin"],
    installType: "installer",
    vendors: [
      {
        id: "miniconda",
        name: "Miniconda",
        homepage: "https://docs.anaconda.com/miniconda",
      },
      {
        id: "anaconda",
        name: "Anaconda Distribution",
        homepage: "https://www.anaconda.com/download",
      },
    ],
  },
  {
    id: "go",
    name: "Go",
    group: "编程语言",
    description: "Go 语言运行时和工具链",
    logoId: "go",
    accentColor: "#00add8",
    envVars: ["GOROOT"],
    pathEntries: ["bin"],
    installType: "archive",
    vendors: [
      {
        id: "golang",
        name: "Go 官方",
        homepage: "https://go.dev/dl",
      },
    ],
  },
  {
    id: "node",
    name: "Node.js",
    group: "JavaScript",
    description: "Node.js 官方运行时和 npm 工具链",
    logoId: "node",
    accentColor: "#339933",
    envVars: ["NODE_HOME"],
    pathEntries: [""],
    installType: "archive",
    vendors: [
      {
        id: "nodejs",
        name: "Node.js 官方",
        homepage: "https://nodejs.org/download/release/",
      },
    ],
  },
  {
    id: "nvm",
    name: "nvm-windows",
    group: "JavaScript",
    description: "Windows Node.js 多版本管理器",
    logoId: "nvm",
    accentColor: "#2f855a",
    envVars: ["NVM_HOME", "NVM_SYMLINK"],
    pathEntries: ["", "nodejs"],
    installType: "archive",
    vendors: [
      {
        id: "coreybutler",
        name: "nvm-windows",
        homepage: "https://github.com/coreybutler/nvm-windows",
      },
    ],
  },
  {
    id: "maven",
    name: "Maven",
    group: "构建工具",
    description: "Java 项目构建和依赖管理",
    logoId: "maven",
    accentColor: "#c71a36",
    envVars: ["MAVEN_HOME"],
    pathEntries: ["bin"],
    installType: "archive",
    vendors: [
      {
        id: "apache",
        name: "Apache Maven",
        homepage: "https://maven.apache.org/download.cgi",
      },
    ],
  },
  {
    id: "gradle",
    name: "Gradle",
    group: "构建工具",
    description: "Gradle 构建工具和 Wrapper 生态",
    logoId: "gradle",
    accentColor: "#02303a",
    envVars: ["GRADLE_HOME"],
    pathEntries: ["bin"],
    installType: "archive",
    vendors: [
      {
        id: "gradle",
        name: "Gradle 官方",
        homepage: "https://gradle.org/releases/",
      },
    ],
  },
  {
    id: "cmake",
    name: "CMake",
    group: "构建工具",
    description: "跨平台 C/C++ 构建系统",
    logoId: "cmake",
    accentColor: "#064f8c",
    envVars: ["CMAKE_HOME"],
    pathEntries: ["bin"],
    installType: "archive",
    vendors: [
      {
        id: "kitware",
        name: "Kitware CMake",
        homepage: "https://cmake.org/download/",
      },
    ],
  },
  {
    id: "ninja",
    name: "Ninja",
    group: "构建工具",
    description: "高速小型构建执行器",
    logoId: "ninja",
    accentColor: "#d64a1a",
    envVars: ["NINJA_HOME"],
    pathEntries: [""],
    installType: "archive",
    vendors: [
      {
        id: "ninja-build",
        name: "Ninja Build",
        homepage: "https://github.com/ninja-build/ninja/releases",
      },
    ],
  },
  {
    id: "cpp",
    name: "C++",
    group: "编程语言",
    description: "LLVM-MinGW C/C++ 编译工具链",
    logoId: "cpp",
    accentColor: "#00599c",
    envVars: ["LLVM_MINGW_HOME"],
    pathEntries: ["bin"],
    installType: "archive",
    vendors: [
      {
        id: "llvm-mingw",
        name: "LLVM-MinGW",
        homepage: "https://github.com/mstorsjo/llvm-mingw",
      },
    ],
  },
  {
    id: "lua",
    name: "Lua",
    group: "编程语言",
    description: "Lua 解释器和字节码编译器",
    logoId: "lua",
    accentColor: "#000080",
    envVars: ["LUA_HOME"],
    pathEntries: [""],
    installType: "archive",
    vendors: [
      {
        id: "luabinaries",
        name: "LuaBinaries",
        homepage: "https://luabinaries.sourceforge.net/download.html",
      },
    ],
  },
  {
    id: "rust",
    name: "Rust",
    group: "编程语言",
    description: "Rustup、Cargo 和 Rust 工具链",
    logoId: "rust",
    accentColor: "#a72145",
    envVars: ["CARGO_HOME", "RUSTUP_HOME"],
    pathEntries: ["cargo\\bin"],
    installType: "installer",
    vendors: [
      {
        id: "rustup",
        name: "Rustup",
        homepage: "https://rustup.rs",
      },
    ],
  },
  {
    id: "dotnet",
    name: ".NET SDK",
    group: "编程语言",
    description: ".NET SDK、CLI 和运行时",
    logoId: "dotnet",
    accentColor: "#512bd4",
    envVars: ["DOTNET_ROOT"],
    pathEntries: [""],
    installType: "archive",
    vendors: [
      {
        id: "microsoft",
        name: "Microsoft .NET",
        homepage: "https://dotnet.microsoft.com/download",
      },
    ],
  },
  {
    id: "php",
    name: "PHP",
    group: "编程语言",
    description: "PHP Windows ZIP 发行版",
    logoId: "php",
    accentColor: "#777bb4",
    envVars: ["PHP_HOME"],
    pathEntries: [""],
    installType: "archive",
    vendors: [
      {
        id: "windows",
        name: "PHP for Windows",
        homepage: "https://windows.php.net/download/",
      },
    ],
  },
  {
    id: "ruby",
    name: "Ruby",
    group: "编程语言",
    description: "RubyInstaller for Windows",
    logoId: "ruby",
    accentColor: "#cc342d",
    envVars: ["RUBY_HOME"],
    pathEntries: ["bin"],
    installType: "installer",
    vendors: [
      {
        id: "rubyinstaller",
        name: "RubyInstaller",
        homepage: "https://rubyinstaller.org/downloads/",
      },
    ],
  },
  {
    id: "flutter",
    name: "Flutter",
    group: "移动开发",
    description: "Flutter SDK 和 Dart 工具链",
    logoId: "flutter",
    accentColor: "#02569b",
    envVars: ["FLUTTER_HOME"],
    pathEntries: ["bin"],
    installType: "archive",
    vendors: [
      {
        id: "google",
        name: "Flutter 官方",
        homepage: "https://docs.flutter.dev/get-started/install/windows",
      },
    ],
  },
  {
    id: "android",
    name: "Android SDK",
    group: "移动开发",
    description: "Android Command Line Tools 和 SDK 根目录",
    logoId: "android",
    accentColor: "#3ddc84",
    envVars: ["ANDROID_HOME", "ANDROID_SDK_ROOT"],
    pathEntries: ["cmdline-tools\\bin", "platform-tools"],
    installType: "archive",
    vendors: [
      {
        id: "google",
        name: "Android Command Line Tools",
        homepage: "https://developer.android.com/studio",
      },
    ],
  },
  {
    id: "mysql",
    name: "MySQL",
    group: "数据库",
    description: "MySQL Community Server ZIP 部署",
    logoId: "mysql",
    accentColor: "#00758f",
    envVars: ["MYSQL_HOME"],
    pathEntries: ["bin"],
    installType: "archive",
    vendors: [
      {
        id: "community",
        name: "MySQL Community Server",
        homepage: "https://dev.mysql.com/downloads/mysql/",
      },
    ],
  },
  {
    id: "postgresql",
    name: "PostgreSQL",
    group: "数据库",
    description: "PostgreSQL Windows 二进制包部署",
    logoId: "postgresql",
    accentColor: "#336791",
    envVars: ["PG_HOME"],
    pathEntries: ["bin"],
    installType: "archive",
    vendors: [
      {
        id: "edb",
        name: "EDB PostgreSQL Binaries",
        homepage: "https://www.enterprisedb.com/download-postgresql-binaries",
      },
    ],
  },
  {
    id: "mongodb",
    name: "MongoDB",
    group: "数据库",
    description: "MongoDB Community Server ZIP 部署",
    logoId: "mongodb",
    accentColor: "#47a248",
    envVars: ["MONGODB_HOME"],
    pathEntries: ["bin"],
    installType: "archive",
    vendors: [
      {
        id: "community",
        name: "MongoDB Community Server",
        homepage: "https://www.mongodb.com/try/download/community",
      },
    ],
  },
  {
    id: "redis",
    name: "Redis",
    group: "数据库",
    description: "Windows Redis 兼容开发运行时",
    logoId: "redis",
    accentColor: "#dc382d",
    envVars: ["REDIS_HOME"],
    pathEntries: [""],
    installType: "archive",
    vendors: [
      {
        id: "redis-windows",
        name: "Redis Windows",
        homepage: "https://github.com/tporadowski/redis/releases",
      },
    ],
  },
  {
    id: "sqlite",
    name: "SQLite",
    group: "数据库",
    description: "SQLite 命令行工具包",
    logoId: "sqlite",
    accentColor: "#003b57",
    envVars: ["SQLITE_HOME"],
    pathEntries: [""],
    installType: "archive",
    vendors: [
      {
        id: "sqlite",
        name: "SQLite Tools",
        homepage: "https://www.sqlite.org/download.html",
      },
    ],
  },
];
